### ISSUE TITLE
请问开发环境是什么？

### ISSUE THREAD

**Issue by sucof** [ilovevue/guanying#1]
请问开发环境是什么？按照npm install 等操作感觉小问题很多。

**Comment by hfstack** [comment]
npm  run dev

**Comment by hfstack** [comment]
控制台截图发过来

**Comment by sucof** [comment]
使用npm run dev的错误
![image](https://user-images.githubusercontent.com/4755824/34649039-75bbfc5e-f3e1-11e7-9997-2df09bf95831.png)

**Comment by hfstack** [comment]
我ingnore了 现在好了

**Comment by sucof** [comment]
还是有问题：
```
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:237:13
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/ro4k/guanying/publicKey.pub'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/ro4k/guanying/src/app.js:27:22)
    at Module._compile (module.js:643:30)
    at loader (/home/ro4k/guanying/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ro4k/guanying/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ro4k/guanying/build/dev-server.js:2:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[20:07:45] [nodemon] app crashed - waiting for file changes before starting...
```
增加publicKey.pub，会出现连接mysql错误：
`Unhandled rejection SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MySQL client`，这个可能是mysql的安全设置？建议不要用root用户，换个普通的mysql用户？

**Comment by hfstack** [comment]
publicKey.pub 是jwt验证用的 我去除了
// const publicKey = fs.readFileSync(path.join(__dirname, '../publicKey.pub'))
// .use(jwt({ secret: publicKey }).unless({ path: [/^\/public|\/user\/login|\/assets/] }))
